name: Penn's Security and Privacy Lab
url: https://splab.cis.upenn.edu/
description: >
    The security and privacy lab at the University of Pennsylvania performs fundamental research in the areas of cryptography, blockchain, anonymous communication, differential privacy, and programming language security.

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: postdoc
    name: Researchers
  - key: grad
    name: Graduate Students
  - key: ugrad
    name: Undergraduate Students
  - key: collab
    name: Affiliated Faculty
  - key: alum
    name: Alumni

research:
  - Anonymous communication
  - Blockchains
  - Differential privacy
  - Multiparty computation
  - Private federated analytics
  - Private information retrieval
  - Zero-knowledge proofs
  - Programming language security
  - Formal verification

courses:
  - number: CIS 2330
    name: Introduction to blockchain
    url: "https://splab.cis.upenn.edu/" # FIXME
  - number: CIS 4510
    name: Computer Network Security
    url: "https://www.cis.upenn.edu/~sga001/classes/cis551s24/"
  - number: CIS 5560
    name: Cryptography
    url: "https://pratyushmishra.com/classes/cis-5560-s24/"
  - number: MCIT 5820
    name: Blockchains
    url: "https://www.cis.upenn.edu/~fbrett/mcit582.html"

# Number of news stories on the front page.
front_page_news: 0

# Base pathname for links.
base: ''

# make pages for the _people folder
collections:
  - people
    
# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /#people
  - title: Research
    link: /#research
  - title: Publications
    link: /publications.html
